version : 2.1
orbs:
    snyk: snyk/snyk@0.0.8
jobs:
  build:
    docker:
      - image: circleci/node:12.13
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - snyk/scan
      
      - run: npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - 61:4b:0a:03:e4:67:1f:e1:6c:41:16:8c:a7:2d:89:e0
      - run:
          name: Deploy to Local
          command: |
            rsync -avz -e "ssh" ~/repo/dist $SSH_USER@$SSH_HOST:/dev

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: build
      - deploy:
          context: deploy
